//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitsID { get; set; }
        public int TopID { get; set; }
        public int BottomID { get; set; }
        public int ShoeID { get; set; }
        public int HeadAccessoryID { get; set; }
        public int NeckAccessoryID { get; set; }
        public int ArmAccessoryID { get; set; }
    
        public virtual ArmAccessory ArmAccessory { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual HeadAccessory HeadAccessory { get; set; }
        public virtual NeckAccessory NeckAccessory { get; set; }
        public virtual Sho Sho { get; set; }
        public virtual Top Top { get; set; }
    }
}
